### ISSUE TITLE
[Bug] Проблема с отображением актуального статуса заказа у логиста-оператора

### ISSUE THREAD

**Issue by LouieChannel** [LouieChannel/client-front#1]
На данный момент возникла проблема с тем, что на странице логиста-оператора не отображается изменённый статус задачи (без перезагрузки экрана).
Если перезагрузить страницу самостоятельно, то всё хорошо, но автоматического обновления нет.  

**Фактический результат:** страница логиста-оператора не отображает актуальный статус задача автоматически (без перезагрузки страницы).

**Ожидаемый результат:** страница логиста-оператора обновляет актуальный статус задачи автоматически

**Comment by Kuzmrom7** [comment]
Fixed! [commit](https://github.com/LouieChannel/client-front/commit/a9ef77c5bf39a76a70cedd1952e2ce1393af3372)
Close#1
