### ISSUE TITLE
[Bug] Проблема с отображением нескольких состояний самосвалов одновременно

### ISSUE THREAD

**Issue by LouieChannel** [LouieChannel/client-front#2]
Возникает проблема во время одновременное работы двух водителей.

Данная проблема проявляет себя таким образом: водитель номер 1 переводит задачу в статус "В процессе выполнения" у логиста-оператора появляется корректное состояние самосвала в данный момент далее приступает к работе водитель номер 2 и также переводит задачу в статус "В процессе выполнения" у логитса-оператора появляется дублирующая картинка первой задачи. 

Когда  меняется состояние самосвала у водителя номер 2 картинка состояния самосвала растягивается по размеру нужной картинки но не меняет сам рисунок. На [картинке с ошибкой](https://user-images.githubusercontent.com/25954892/82264852-5f260180-996e-11ea-8347-b0dadb678c46.png) продемонстрирован пример данный ошибки. Можно заметить что по логам пришло **3 состояния**: **1 состояние** принадлежит задаче **номер 65**, два других состояния принадлежат задаче **номер 64**. На рисунке правильно отображается картинка только для задачи **номер 65** которая идёт первая по списку сверху, но после неё идёт задач **номер 64** и у неё **состояние 3 а это совершенно другой рисунок**

**Фактический результат:** При работа от 2-ух водителей и более идёт неверное отображение состояний грузовой техники.

**Ожидаемый результат:** При работе от 2-ух водителей и более идёт корректное отображение состояний грузовой техники

**Comment by Kuzmrom7** [comment]
[Fixed](https://github.com/LouieChannel/client-front/commit/1437cc0db5a36186b9fab26694257ea0c7e31210)
